apiVersion : apps/v1
kind: Deployment
metadata:
  name: neiltingleypipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neiltingleypipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: neiltingleypipelinesjavascriptdocker 
    spec:
      containers:
        - name: neiltingleypipelinesjavascriptdocker 
          image: devopsworksio.azurecr.io/neiltingleypipelinesjavascriptdocker
          ports:
          - containerPort: 8080